// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231128192243_FilmSeeded")]
    partial class FilmSeeded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Data.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Book ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("author")
                        .HasComment("Book author");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title")
                        .HasComment("Book title");

                    b.Property<int?>("YearPublished")
                        .HasColumnType("integer")
                        .HasColumnName("year_published")
                        .HasComment("Book year of publishing");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.ToTable("books", null, t =>
                        {
                            t.HasComment("Books table");
                        });
                });

            modelBuilder.Entity("Infrastructure.Data.Models.DefaultValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("The unique identifier for the table.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreditsWithSentinel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("credits_with_sentinel")
                        .HasComment("The default value for the integer with custom sentinel");

                    b.Property<int>("CreditsWithoutSentinel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("credits_without_sentinel")
                        .HasComment("The default value for the integer.");

                    b.Property<bool>("IsActiveDefaultFalse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active_default_false")
                        .HasComment("The default value for the bool false.");

                    b.Property<bool>("IsActiveDefaultTrue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active_default_true")
                        .HasComment("The default value for the bool true.");

                    b.HasKey("Id")
                        .HasName("pk_default_values");

                    b.ToTable("default_values", null, t =>
                        {
                            t.HasComment("Default value.");
                        });
                });

            modelBuilder.Entity("Infrastructure.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("The unique identifier for the employee.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email")
                        .HasComment("Current email address of the employee.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasComment("The name of the employee.");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.ToTable("employees", null, t =>
                        {
                            t.HasComment("An employee.");
                        });
                });

            modelBuilder.Entity("Infrastructure.Data.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("The unique identifier for the film.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration")
                        .HasComment("The duration of the film.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title")
                        .HasComment("The title of the film.");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year")
                        .HasComment("The year of the film.");

                    b.HasKey("Id")
                        .HasName("pk_films");

                    b.ToTable("films", null, t =>
                        {
                            t.HasComment("A film.");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 1",
                            Year = 1921
                        },
                        new
                        {
                            Id = 2,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 2",
                            Year = 1922
                        },
                        new
                        {
                            Id = 3,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 3",
                            Year = 1923
                        },
                        new
                        {
                            Id = 4,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 4",
                            Year = 1924
                        },
                        new
                        {
                            Id = 5,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 5",
                            Year = 1925
                        },
                        new
                        {
                            Id = 6,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 6",
                            Year = 1926
                        },
                        new
                        {
                            Id = 7,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 7",
                            Year = 1927
                        },
                        new
                        {
                            Id = 8,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 8",
                            Year = 1928
                        },
                        new
                        {
                            Id = 9,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 9",
                            Year = 1929
                        },
                        new
                        {
                            Id = 10,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 10",
                            Year = 1930
                        },
                        new
                        {
                            Id = 11,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 11",
                            Year = 1931
                        },
                        new
                        {
                            Id = 12,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 12",
                            Year = 1932
                        },
                        new
                        {
                            Id = 13,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 13",
                            Year = 1933
                        },
                        new
                        {
                            Id = 14,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 14",
                            Year = 1934
                        },
                        new
                        {
                            Id = 15,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 15",
                            Year = 1935
                        },
                        new
                        {
                            Id = 16,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 16",
                            Year = 1936
                        },
                        new
                        {
                            Id = 17,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 17",
                            Year = 1937
                        },
                        new
                        {
                            Id = 18,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 18",
                            Year = 1938
                        },
                        new
                        {
                            Id = 19,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 19",
                            Year = 1939
                        },
                        new
                        {
                            Id = 20,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 20",
                            Year = 1940
                        },
                        new
                        {
                            Id = 21,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 21",
                            Year = 1941
                        },
                        new
                        {
                            Id = 22,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 22",
                            Year = 1942
                        },
                        new
                        {
                            Id = 23,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 23",
                            Year = 1943
                        },
                        new
                        {
                            Id = 24,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 24",
                            Year = 1944
                        },
                        new
                        {
                            Id = 25,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 25",
                            Year = 1945
                        },
                        new
                        {
                            Id = 26,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 26",
                            Year = 1946
                        },
                        new
                        {
                            Id = 27,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 27",
                            Year = 1947
                        },
                        new
                        {
                            Id = 28,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 28",
                            Year = 1948
                        },
                        new
                        {
                            Id = 29,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 29",
                            Year = 1949
                        },
                        new
                        {
                            Id = 30,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 30",
                            Year = 1950
                        },
                        new
                        {
                            Id = 31,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 31",
                            Year = 1951
                        },
                        new
                        {
                            Id = 32,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 32",
                            Year = 1952
                        },
                        new
                        {
                            Id = 33,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 33",
                            Year = 1953
                        },
                        new
                        {
                            Id = 34,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 34",
                            Year = 1954
                        },
                        new
                        {
                            Id = 35,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 35",
                            Year = 1955
                        },
                        new
                        {
                            Id = 36,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 36",
                            Year = 1956
                        },
                        new
                        {
                            Id = 37,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 37",
                            Year = 1957
                        },
                        new
                        {
                            Id = 38,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 38",
                            Year = 1958
                        },
                        new
                        {
                            Id = 39,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 39",
                            Year = 1959
                        },
                        new
                        {
                            Id = 40,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 40",
                            Year = 1960
                        },
                        new
                        {
                            Id = 41,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 41",
                            Year = 1961
                        },
                        new
                        {
                            Id = 42,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 42",
                            Year = 1962
                        },
                        new
                        {
                            Id = 43,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 43",
                            Year = 1963
                        },
                        new
                        {
                            Id = 44,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 44",
                            Year = 1964
                        },
                        new
                        {
                            Id = 45,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 45",
                            Year = 1965
                        },
                        new
                        {
                            Id = 46,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 46",
                            Year = 1966
                        },
                        new
                        {
                            Id = 47,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 47",
                            Year = 1967
                        },
                        new
                        {
                            Id = 48,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 48",
                            Year = 1968
                        },
                        new
                        {
                            Id = 49,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 49",
                            Year = 1969
                        },
                        new
                        {
                            Id = 50,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 50",
                            Year = 1970
                        },
                        new
                        {
                            Id = 51,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 51",
                            Year = 1971
                        },
                        new
                        {
                            Id = 52,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 52",
                            Year = 1972
                        },
                        new
                        {
                            Id = 53,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 53",
                            Year = 1973
                        },
                        new
                        {
                            Id = 54,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 54",
                            Year = 1974
                        },
                        new
                        {
                            Id = 55,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 55",
                            Year = 1975
                        },
                        new
                        {
                            Id = 56,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 56",
                            Year = 1976
                        },
                        new
                        {
                            Id = 57,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 57",
                            Year = 1977
                        },
                        new
                        {
                            Id = 58,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 58",
                            Year = 1978
                        },
                        new
                        {
                            Id = 59,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 59",
                            Year = 1979
                        },
                        new
                        {
                            Id = 60,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 60",
                            Year = 1980
                        },
                        new
                        {
                            Id = 61,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 61",
                            Year = 1981
                        },
                        new
                        {
                            Id = 62,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 62",
                            Year = 1982
                        },
                        new
                        {
                            Id = 63,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 63",
                            Year = 1983
                        },
                        new
                        {
                            Id = 64,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 64",
                            Year = 1984
                        },
                        new
                        {
                            Id = 65,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 65",
                            Year = 1985
                        },
                        new
                        {
                            Id = 66,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 66",
                            Year = 1986
                        },
                        new
                        {
                            Id = 67,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 67",
                            Year = 1987
                        },
                        new
                        {
                            Id = 68,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 68",
                            Year = 1988
                        },
                        new
                        {
                            Id = 69,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 69",
                            Year = 1989
                        },
                        new
                        {
                            Id = 70,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 70",
                            Year = 1990
                        },
                        new
                        {
                            Id = 71,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 71",
                            Year = 1991
                        },
                        new
                        {
                            Id = 72,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 72",
                            Year = 1992
                        },
                        new
                        {
                            Id = 73,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 73",
                            Year = 1993
                        },
                        new
                        {
                            Id = 74,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 74",
                            Year = 1994
                        },
                        new
                        {
                            Id = 75,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 75",
                            Year = 1995
                        },
                        new
                        {
                            Id = 76,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 76",
                            Year = 1996
                        },
                        new
                        {
                            Id = 77,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 77",
                            Year = 1997
                        },
                        new
                        {
                            Id = 78,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 78",
                            Year = 1998
                        },
                        new
                        {
                            Id = 79,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 79",
                            Year = 1999
                        },
                        new
                        {
                            Id = 80,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 80",
                            Year = 2000
                        },
                        new
                        {
                            Id = 81,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 81",
                            Year = 2001
                        },
                        new
                        {
                            Id = 82,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 82",
                            Year = 2002
                        },
                        new
                        {
                            Id = 83,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 83",
                            Year = 2003
                        },
                        new
                        {
                            Id = 84,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 84",
                            Year = 2004
                        },
                        new
                        {
                            Id = 85,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 85",
                            Year = 2005
                        },
                        new
                        {
                            Id = 86,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 86",
                            Year = 2006
                        },
                        new
                        {
                            Id = 87,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 87",
                            Year = 2007
                        },
                        new
                        {
                            Id = 88,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 88",
                            Year = 2008
                        },
                        new
                        {
                            Id = 89,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 89",
                            Year = 2009
                        },
                        new
                        {
                            Id = 90,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 90",
                            Year = 2010
                        },
                        new
                        {
                            Id = 91,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 91",
                            Year = 2011
                        },
                        new
                        {
                            Id = 92,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 92",
                            Year = 2012
                        },
                        new
                        {
                            Id = 93,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 93",
                            Year = 2013
                        },
                        new
                        {
                            Id = 94,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 94",
                            Year = 2014
                        },
                        new
                        {
                            Id = 95,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 95",
                            Year = 2015
                        },
                        new
                        {
                            Id = 96,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 96",
                            Year = 2016
                        },
                        new
                        {
                            Id = 97,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 97",
                            Year = 2017
                        },
                        new
                        {
                            Id = 98,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 98",
                            Year = 2018
                        },
                        new
                        {
                            Id = 99,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 99",
                            Year = 2019
                        },
                        new
                        {
                            Id = 100,
                            Duration = 120,
                            IsActive = true,
                            Title = "Film 100",
                            Year = 2020
                        });
                });

            modelBuilder.Entity("Infrastructure.Data.Models.MedicalPractitioner", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("medical_practitioner_name")
                        .HasComment("Medical practitioner name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("medical_practitioner_telephone")
                        .HasComment("Medical practitioner telephone");

                    b.Property<string>("Uin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("uin")
                        .HasComment("Medical practitioner UIN");

                    b.HasKey("Id")
                        .HasName("pk_prescriptions");

                    b.ToTable("Prescriptions", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("patient_age")
                        .HasComment("Patient age");

                    b.Property<string>("Ekatte")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("patient_ekatte")
                        .HasComment("Patient EKATTE");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("patient_gender")
                        .HasComment("Patient gender");

                    b.Property<Guid>("Mpi")
                        .HasColumnType("uuid")
                        .HasColumnName("mpi")
                        .HasComment("Patient identifier");

                    b.HasKey("Id")
                        .HasName("pk_prescriptions");

                    b.ToTable("Prescriptions", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("The unique identifier for the person.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasComment("The name of the person.");

                    b.ComplexProperty<Dictionary<string, object>>("CurrentAddress", "Infrastructure.Data.Models.Person.CurrentAddress#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("current_address_city")
                                .HasComment("The city of the address.");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("current_address_country")
                                .HasComment("The country of the address.");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("current_address_line1")
                                .HasComment("The first line of the address.");

                            b1.Property<string>("Line2")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("current_address_line2")
                                .HasComment("The second line of the address.");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("current_address_post_code")
                                .HasComment("The post code of the address.");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PermanentAddress", "Infrastructure.Data.Models.Person.PermanentAddress#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("permanent_address_city")
                                .HasComment("The city of the address.");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("permanent_address_country")
                                .HasComment("The country of the address.");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("permanent_address_line1")
                                .HasComment("The first line of the address.");

                            b1.Property<string>("Line2")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("permanent_address_line2")
                                .HasComment("The second line of the address.");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("permanent_address_post_code")
                                .HasComment("The post code of the address.");
                        });

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.ToTable("people", null, t =>
                        {
                            t.HasComment("A person.");
                        });
                });

            modelBuilder.Entity("Infrastructure.Data.Models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Prescription ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Medication")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("medication")
                        .HasComment("Prescribed medication");

                    b.Property<string>("Nrn")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("nrn")
                        .HasComment("National referent number");

                    b.Property<int>("PatientAge")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("patient_age")
                        .HasComment("Patient age");

                    b.HasKey("Id")
                        .HasName("pk_prescriptions");

                    b.ToTable("Prescriptions", null, t =>
                        {
                            t.HasComment("Prescriptions table");
                        });
                });

            modelBuilder.Entity("Infrastructure.Data.Models.PrimitiveCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("The unique identifier for the table.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime[]>("DateTimes")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]")
                        .HasColumnName("date_times")
                        .HasComment("Collection of timestamps.");

                    b.Property<DateOnly[]>("Dates")
                        .IsRequired()
                        .HasColumnType("date[]")
                        .HasColumnName("dates")
                        .HasComment("Collection of dates.");

                    b.Property<int[]>("Ints")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("ints")
                        .HasComment("Collection of integers.");

                    b.Property<string[]>("Strings")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("strings")
                        .HasComment("Collection of strings.");

                    b.HasKey("Id")
                        .HasName("pk_primitive_collections");

                    b.ToTable("primitive_collections", null, t =>
                        {
                            t.HasComment("Collections of primitive types.");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTimes = new[] { new DateTime(2021, 1, 1, 1, 1, 1, 0, DateTimeKind.Utc), new DateTime(2021, 2, 1, 2, 2, 2, 0, DateTimeKind.Utc), new DateTime(2021, 3, 1, 3, 3, 3, 0, DateTimeKind.Utc) },
                            Dates = new[] { new DateOnly(2021, 1, 1), new DateOnly(2021, 2, 1), new DateOnly(2021, 3, 1) },
                            Ints = new[] { 1, 2, 3 },
                            Strings = new[] { "one", "two", "three" }
                        },
                        new
                        {
                            Id = 2,
                            DateTimes = new[] { new DateTime(2021, 4, 1, 4, 4, 4, 0, DateTimeKind.Utc), new DateTime(2021, 5, 1, 5, 5, 5, 0, DateTimeKind.Utc), new DateTime(2021, 6, 1, 6, 6, 6, 0, DateTimeKind.Utc) },
                            Dates = new[] { new DateOnly(2021, 4, 1), new DateOnly(2021, 5, 1), new DateOnly(2021, 6, 1) },
                            Ints = new[] { 4, 5, 6 },
                            Strings = new[] { "four", "five", "six" }
                        },
                        new
                        {
                            Id = 3,
                            DateTimes = new[] { new DateTime(2021, 7, 1, 7, 7, 7, 0, DateTimeKind.Utc), new DateTime(2021, 8, 1, 8, 8, 8, 0, DateTimeKind.Utc), new DateTime(2021, 9, 1, 9, 9, 9, 0, DateTimeKind.Utc) },
                            Dates = new[] { new DateOnly(2021, 7, 1), new DateOnly(2021, 8, 1), new DateOnly(2021, 9, 1) },
                            Ints = new[] { 7, 8, 9 },
                            Strings = new[] { "seven", "eight", "nine" }
                        });
                });

            modelBuilder.Entity("Infrastructure.Data.Models.Employee", b =>
                {
                    b.OwnsOne("Infrastructure.Data.Models.Workplace", "Workplace", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .HasColumnType("integer");

                            b1.Property<string>("Address")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasComment("The address of the workplace.");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasComment("The city of the workplace.");

                            b1.Property<int?>("Floor")
                                .HasColumnType("integer")
                                .HasComment("The floor of the workplace.");

                            b1.Property<string>("Office")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasComment("The name of the workplace.");

                            b1.Property<string[]>("Phones")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasComment("The phone numbers of the workplace.");

                            b1.Property<int>("RoomNumber")
                                .HasColumnType("integer")
                                .HasComment("The room number of the workplace.");

                            b1.HasKey("EmployeeId")
                                .HasName("pk_employees");

                            b1.ToTable("employees", t =>
                                {
                                    t.HasComment("A workplace.");
                                });

                            b1.ToJson("workplace");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId")
                                .HasConstraintName("fk_employees_employees_employee_id");
                        });

                    b.Navigation("Workplace")
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Data.Models.MedicalPractitioner", b =>
                {
                    b.HasOne("Infrastructure.Data.Models.Prescription", null)
                        .WithOne("MedicalPractitioner")
                        .HasForeignKey("Infrastructure.Data.Models.MedicalPractitioner", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prescriptions_prescriptions_id");
                });

            modelBuilder.Entity("Infrastructure.Data.Models.Patient", b =>
                {
                    b.HasOne("Infrastructure.Data.Models.Prescription", null)
                        .WithOne("Patient")
                        .HasForeignKey("Infrastructure.Data.Models.Patient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prescriptions_prescriptions_id");
                });

            modelBuilder.Entity("Infrastructure.Data.Models.Prescription", b =>
                {
                    b.Navigation("MedicalPractitioner")
                        .IsRequired();

                    b.Navigation("Patient")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
